#ifndef _DPFM_CONST_H_
#define _DPFM_CONST_H_

#define DPFM_OK 0
#define DPFM_FILE_NOT_EXIST 1
#define DPFM_FILE_OPEN_FAILED 2
#define DPFM_FILE_WRITE_ERROR 3
#define DPFM_PACK_NOT_EXIST 4
#define DPFM_MEM_ALLOC_ERROR 5
#define DPFM_FILE_READ_ERROR 6
#define DPFM_FILE_NOT_IN_PACK 7
#define DPFM_FILE_PATH_INVALID 8

#endif